export default ({
  'hairdryer': '/facilities/fan.png',
  'teapot': '/facilities/teapot.png',
  'coffee': '/facilities/coffee.png',
  'iron': '/facilities/iron.png',
  'frige': '/facilities/fridge.png',
  'tv': '/facilities/tv.png',
  'audio': '/facilities/audio.png',
  'playstation': '/facilities/playstation.png',
  'ironingBoard': '/facilities/ironingBoard.png',
  'washer': '/facilities/washer.png',
  'drying': '/facilities/drying.png',
  'dishwasher': '/facilities/dishwasher.png',
  'gasStove': '/facilities/gasStove.png',
  'electricStove': '/facilities/electricStove.png',
  'oven': '/facilities/oven.png',
  'microwave': '/facilities/microwave.png',
  'fire': '/facilities/fire.png',
  'privatHeat': '/facilities/privatHeat.png',
  'commonHeat': '/facilities/commonHeat.png',
  'dishes': '/facilities/dishes.png',
  'tableware': '/facilities/tableware.png',
  'allForCooking': '/facilities/allForCooking.png',
  'teaCups': '/facilities/teaCups.png'
})
