apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: prod
spec:
  ports:
    - port: 80
      name: plaintext
      targetPort: 3000
  selector:
    app: front
  type: LoadBalancer
  externalTrafficPolicy: Cluster

