<template>
  <div class="loadingio-spinner-rolling-tv3ehanuyhg">
    <div class="ldio-he32kuqf4s6">
      <div />
    </div>
  </div>
</template>

<style type="text/css" scoped>
  @keyframes ldio-he32kuqf4s6 {
    0% { transform: translate(-50%,-50%) rotate(0deg); }
    100% { transform: translate(-50%,-50%) rotate(360deg); }
  }
  .ldio-he32kuqf4s6 div {
    position: absolute;
    width: 100.89px;
    height: 100.89px;
    border: 19.47px solid #1d0e0b;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-he32kuqf4s6 div {
    animation: ldio-he32kuqf4s6 1s linear infinite;
    top: 88.5px;
    left: 88.5px
  }
  .loadingio-spinner-rolling-tv3ehanuyhg {
    width: 177px;
    height: 177px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-he32kuqf4s6 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-he32kuqf4s6 div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
